### ISSUE TITLE
Missing/wrong argument in icasso.plot_mds in example file

### ISSUE THREAD

**Issue by jeffreydurieux** [Teekuningas/icasso#4]
Dear Teekuningas,

First of all, thank you for this ICASSO implementation. I was trying to run the example file and it gave an error. The error happens at line 80:
icasso.plot_mds(distance=distance, random_state=random_state)

random_state is not an existing argument value in the function.

Hope this helps

**Comment by teekuningas** [comment]
Thanks! Should be fixed now.. examples were lagging behind.
